### ISSUE TITLE
-f is too eager: "vv" DOES occur in English

### ISSUE THREAD

**Issue by cheweytoo** [DrLex0/SRTLab#1]
-f now transforms all occurences of "vv" into "w".

Since there are English words with "vv"¹, this breaks correct spelling.
Most "vv" words are admittedly obscure, but I just had it happen with "savvy", one of the not-so-obscure ones.

¹: https://scrabble.merriam.com/words/with/vv

**Comment by DrLex0** [comment]
Given that the list is rather limited, it makes more sense to prevent those specific words from being over-corrected, than to just disable this correction entirely. Or, apply the correction and then undo it for those words, which would also fix the case where OCR turns ‘vv’ into ‘w’ (although I haven't seen that happen yet).

**Comment by cheweytoo** [comment]
The list is undefined and/or unlimited. The list of _dictionary_ words may be limited, but those are not the only ones that will be encountered.

A list of all possible proper nouns is obviously impossible, and those exist too:
https://en.wikipedia.org/wiki/List_of_Star_Wars_species_(P%E2%80%93T)#Snivvian
https://en.wikipedia.org/wiki/Savvin
https://en.wikipedia.org/wiki/Chevvy
https://en.wikipedia.org/wiki/Luvvie_Ajayi
https://open.spotify.com/album/1hbSWvnXQkQwiomK4i0g2f
…

"vv" _will_ occur in English subs in legitimate words that are not on any "don't correct that one" list. You can't rely on a whitelist for this.

**Comment by cheweytoo** [comment]
Sensible solution. Thanks!
